---
title: "R Notebook DS Workflow - update 2"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
```

Data Import

```{r message=FALSE}
records <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-25/records.csv')

```

Data Wrangle

```{r message=FALSE}
records1 <- records %>%
 filter(!(track %in% "Luigi Raceway")) %>%
 filter(date >= "2000-10-10" & 
    date <= "2021-02-25") %>%
 filter(record_duration >= 321L & record_duration <= 
    3659L) 
```


```{r}

p <- ggplot(data = records1, aes(x = track, group = player)) +
            geom_bar(fill = "#0c4c8a") +
  theme_minimal()

p

```


```{r}
ggplotly(p)
```

```{r}

records2 <- records %>%
 filter(type %in% "Three Lap") %>%
 filter(date >= "2011-06-30" & date <= 
    "2021-02-25")

```

```{r}
  p2 <- ggplot(data=records2, aes(x = shortcut, y = time, fill = player)) +
 geom_boxplot() +
 scale_fill_hue() +
 theme_minimal()
```



```{r}
ggplotly(p2)
```



